window.MLDI_RESEARCH = [
  {id:'kairos',title:'Kairos',venue:'NeurIPS 2026',headline:'Forecast across domains with a compact foundation model.',summary:'Adaptive temporal tokenization matches local information density. The result is an open forecasting family that combines zero-shot transfer with parameter efficiency.',evidence:'38,997 cumulative downloads across three official Hugging Face checkpoints.',url:'https://foundation-model-research.github.io/Kairos/'},
  {id:'latent-distilling',title:'ESamp / Latent Distilling',venue:'ICML 2026',headline:'Explore new reasoning paths, beyond different wordings.',summary:'A lightweight latent distiller provides a semantic novelty signal during decoding. ESamp encourages diverse reasoning paths across mathematics, science and code.',evidence:'Exploration happens in representation space, rather than only at the next-token surface.',url:'https://arxiv.org/abs/2604.24927'},
  {id:'crm',title:'Conditional Reward Modeling',venue:'ICLR 2026',headline:'Give each reasoning step credit for the outcome.',summary:'CRM conditions step rewards on preceding reasoning and links them to final correctness. This makes process supervision more consistent and addresses reward hacking in the evaluated settings.',evidence:'AIME24: 43.3% vs 26.6% for PURE in the reported VR-disabled RL comparison.',url:'https://foundation-model-research.github.io/CRM/'},
  {id:'miclip',title:'MICLIP',venue:'ICLR 2026',headline:'Connect hidden model representations to human concepts.',summary:'By grounding internal representations in both input and output semantics, MICLIP supports concept descriptions, localization and targeted model steering.',evidence:'The original visual examples show concept localization inside a vision model.',url:'https://foundation-model-research.github.io/MICLIP/'},
  {id:'difflens',title:'DiffLens',venue:'CVPR 2025',headline:'Test an explanation by intervening on the mechanism.',summary:'DiffLens identifies bias-related internal features and adjusts them to steer generation. Its contribution connects mechanistic understanding with controlled changes in model behavior.',evidence:'In the P2 experiment, the generated male:female ratio changes from 33.9:66.1 to 49.9:50.1. The paired demos illustrate gender and age control.',url:'https://foundation-model-research.github.io/difflens/'},
  {id:'tadiff',title:'TADiff',venue:'ICML 2026',headline:'Forecast a future that has not happened yet.',summary:'Keep the same observed history and change the future condition in language. TADiff separates temporal dynamics from external context to model counterfactual futures.',evidence:'The original teaser compares ordinary traffic with a rainstorm and a nearby World Cup final.',url:'https://seqml.github.io/TADiff/'},
  {id:'verbalts',title:'VerbalTS',venue:'ICML 2025',headline:'Make language a control interface for time series.',summary:'VerbalTS turns unstructured descriptions into temporal data. Natural language expresses the desired patterns for generation and editing.',evidence:'A step toward multimodal time-series intelligence: connect meaning with temporal structure.',url:'https://seqml.github.io/VerbalTS/'},
  {id:'tedit',title:'TEdit',venue:'NeurIPS 2024',headline:'Edit a sequence instead of generating it from scratch.',summary:'TEdit introduces attribute-guided time-series editing. The authors’ original animation changes seasonality while retaining the requested trend.',evidence:'Original demonstration: change seasonal cycles from zero to four.',url:'https://seqml.github.io/tse/'}
];
